In [1]:
import torch

In [2]:
x = torch.Tensor([5, 3])
y = torch.Tensor([2, 1])
print(x*y)

tensor([10.,  3.])


In [3]:
x = torch.zeros([2, 5])

In [4]:
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [5]:
x.shape

torch.Size([2, 5])

In [7]:
y = torch.rand([2, 5])
y

tensor([[0.8432, 0.4124, 0.2766, 0.0877, 0.4942],
        [0.3665, 0.9623, 0.9440, 0.2698, 0.3043]])

In [13]:
y.view([1, 10])

tensor([[0.8432, 0.4124, 0.2766, 0.0877, 0.4942, 0.3665, 0.9623, 0.9440, 0.2698,
         0.3043]])

In [14]:
y.view([10, 1])


tensor([[0.8432],
        [0.4124],
        [0.2766],
        [0.0877],
        [0.4942],
        [0.3665],
        [0.9623],
        [0.9440],
        [0.2698],
        [0.3043]])